//! The current invocation's HTML landing page and item reports.
//!
//! Input is already sanitized. The ownership file records only generated paths,
//! never report history or evidence, so reruns can safely remove obsolete pages.

use super::{render, HtmlReport, STYLE};
use serde_json::{json, Value};
use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

const DIRECTORY: &str = "vault-report-pages";
const STYLESHEET: &str = "style.css";
const OWNERSHIP: &str = ".vault-report-pages.json";
const INDEX_MARKER: &str = "<!-- vault-report-index:v1 -->";
static TEMP_ID: AtomicU64 = AtomicU64::new(0);

struct ItemPage {
    item: Value,
    filename: String,
    report: HtmlReport,
    status: &'static str,
}

pub(super) fn write(report: &HtmlReport, path: &Path) -> io::Result<()> {
    let parent = path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    at(parent, fs::create_dir_all(parent))?;
    regular_file_or_absent(path)?;
    let index_path = parent.join("index.html");
    let mut combined =
        path.file_name().is_some_and(|name| name == "index.html") || aliases(path, &index_path);

    // Every disk report depends on this stylesheet. Publish it before any HTML,
    // retaining ownership of earlier pages if a later ancillary write fails.
    let directory = parent.join(DIRECTORY);
    let mut previous = owned_files(&directory)?;
    let stylesheet_path = directory.join(STYLESHEET);
    regular_file_or_absent(&stylesheet_path)?;
    if stylesheet_path.exists() && !previous.contains(STYLESHEET) {
        return Err(invalid(
            &stylesheet_path,
            "refusing to replace an unowned report stylesheet",
        ));
    }
    at(&directory, fs::create_dir_all(&directory))?;
    previous.insert(STYLESHEET.to_owned());
    write_ownership(&directory, &previous)?;
    atomic_write(&stylesheet_path, STYLE)?;

    let root_stylesheet = format!("{DIRECTORY}/{STYLESHEET}");
    // The requested aggregate remains useful even if an ancillary output fails.
    if !combined {
        atomic_write(
            path,
            &with_navigation(report, "index.html", &root_stylesheet),
        )?;
        // On a case-insensitive filesystem, INDEX.html may be the very same
        // requested output as index.html. Keep the canonical landing-page link.
        combined = aliases(path, &index_path);
    }
    if !combined {
        regular_file_or_absent(&index_path)?;
        if index_path.exists() {
            let mut prefix = String::new();
            at(&index_path, fs::File::open(&index_path))?
                .take(256)
                .read_to_string(&mut prefix)
                .map_err(|error| context(&index_path, error))?;
            if !prefix.contains(INDEX_MARKER) {
                return Err(invalid(
                    &index_path,
                    "refusing to replace an index not generated by Vault",
                ));
            }
        }
    }
    let pages = item_pages(report);
    let current: BTreeSet<String> = pages
        .iter()
        .map(|page| page.filename.clone())
        .chain(std::iter::once(STYLESHEET.to_owned()))
        .collect();
    for name in &current {
        let page = directory.join(name);
        regular_file_or_absent(&page)?;
        if page.exists() && !previous.contains(name) {
            return Err(invalid(&page, "refusing to replace an unowned report page"));
        }
    }

    // Record ownership before publishing pages so a failed write remains
    // recoverable on the next invocation. Obsolete files stay owned until removed.
    let pending: BTreeSet<String> = previous.union(&current).cloned().collect();
    write_ownership(&directory, &pending)?;
    for page in &pages {
        let html = with_navigation(&page.report, "../index.html", STYLESHEET);
        atomic_write(&directory.join(&page.filename), &html)?;
    }

    let listing = index_listing(&pages);
    if combined {
        let html = render(report, &stylesheet_link(&root_stylesheet)).replacen(
            "<main>",
            &format!("<main>\n{listing}"),
            1,
        );
        // Use the canonical spelling on case-insensitive filesystems as well,
        // so copying the directory to a case-sensitive filesystem keeps links valid.
        atomic_write(&index_path, &mark_index(html))?;
    } else {
        let filename = path
            .file_name()
            .ok_or_else(|| invalid(path, "expected an HTML filename"))?;
        let html = index_document(&listing, &url_segment(&filename.to_string_lossy()));
        atomic_write(&index_path, &html)?;
    }

    // Never scan/delete by a filename pattern: only paths from the ownership
    // file may be removed, and links/directories are never followed or deleted.
    for name in previous.difference(&current) {
        let stale = directory.join(name);
        match fs::symlink_metadata(&stale) {
            Ok(metadata) if metadata.file_type().is_file() => at(&stale, fs::remove_file(&stale))?,
            Ok(_) => {
                return Err(invalid(
                    &stale,
                    "obsolete generated page is no longer a regular file",
                ))
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound => {}
            Err(error) => return Err(context(&stale, error)),
        }
    }
    write_ownership(&directory, &current)
}

fn item_pages(report: &HtmlReport) -> Vec<ItemPage> {
    let results = report
        .run
        .get("tests")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut items = report
        .metadata
        .get("items")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut descriptors = report
        .metadata
        .get("tests")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    // Keep the renderer's compatibility with reports built without CLI metadata.
    if descriptors.is_empty() {
        descriptors = results.iter().enumerate().map(|(index, result)| {
            let flow = result.get("flow").and_then(Value::as_str);
            let item_id = flow.map(str::to_owned).unwrap_or_else(|| format!("standalone-{index}"));
            json!({"id":format!("test-{index}"), "item_id":item_id, "name":result["name"],
                "flow":flow, "stage_index":index, "result_index":index,
                "execution_index":if index < report.executions.len() { json!(index) } else { Value::Null }})
        }).collect();
    }
    descriptors.retain(Value::is_object);
    items.retain(Value::is_object);
    for (index, descriptor) in descriptors.iter_mut().enumerate() {
        let id = descriptor
            .get("item_id")
            .and_then(Value::as_str)
            .or_else(|| descriptor.get("flow").and_then(Value::as_str))
            .or_else(|| descriptor.get("id").and_then(Value::as_str))
            .map(str::to_owned)
            .unwrap_or_else(|| format!("standalone-{index}"));
        if !items
            .iter()
            .any(|item| item.get("id").and_then(Value::as_str) == Some(&id))
        {
            let flow = descriptor.get("flow").and_then(Value::as_str);
            items.push(json!({"id":id, "kind":if flow.is_some() {"flow"} else {"test"},
                "name":flow.or_else(|| descriptor.get("name").and_then(Value::as_str)).unwrap_or("Unnamed test")}));
        }
        descriptor["item_id"] = json!(id);
    }
    items
        .into_iter()
        .enumerate()
        .map(|(index, item)| {
            let tests: Vec<Value> = descriptors
                .iter()
                .filter(|test| test.get("item_id") == item.get("id"))
                .cloned()
                .collect();
            let mut selected_results = Vec::new();
            let mut selected_executions = Vec::new();
            let mut result_map = HashMap::new();
            let mut execution_map = HashMap::new();
            let tests: Vec<Value> = tests
                .into_iter()
                .map(|mut test| {
                    remap(
                        &mut test,
                        "result_index",
                        &results,
                        &mut selected_results,
                        &mut result_map,
                    );
                    remap(
                        &mut test,
                        "execution_index",
                        &report.executions,
                        &mut selected_executions,
                        &mut execution_map,
                    );
                    test
                })
                .collect();
            let status = item_status(&tests, &selected_results);
            let duration = selected_results
                .iter()
                .filter_map(|result| result.get("duration_ms").and_then(Value::as_u64))
                .fold(0u64, u64::saturating_add);
            let mut run = report.run.as_object().cloned().unwrap_or_default();
            run.insert("tests".into(), json!(selected_results));
            run.insert("duration_ms".into(), json!(duration));
            let mut metadata = report.metadata.as_object().cloned().unwrap_or_default();
            metadata.insert("items".into(), json!([item]));
            metadata.insert("tests".into(), json!(tests));
            metadata.insert(
                "report_page".into(),
                json!({"title":item["name"], "kind":item["kind"]}),
            );
            let kind = if item.get("kind").and_then(Value::as_str) == Some("flow") {
                "flow"
            } else {
                "test"
            };
            ItemPage {
                item,
                filename: format!("{kind}-{:03}.html", index + 1),
                status,
                report: HtmlReport {
                    schema_version: report.schema_version,
                    run: Value::Object(run),
                    metadata: Value::Object(metadata),
                    executions: selected_executions,
                },
            }
        })
        .collect()
}

fn remap(
    descriptor: &mut Value,
    field: &str,
    source: &[Value],
    selected: &mut Vec<Value>,
    mapping: &mut HashMap<usize, usize>,
) {
    let index = descriptor
        .get(field)
        .and_then(Value::as_u64)
        .and_then(|index| usize::try_from(index).ok());
    descriptor[field] = index
        .filter(|index| *index < source.len())
        .map(|index| {
            let new_index = *mapping.entry(index).or_insert_with(|| {
                selected.push(source[index].clone());
                selected.len() - 1
            });
            json!(new_index)
        })
        .unwrap_or(Value::Null);
}

fn item_status(tests: &[Value], results: &[Value]) -> &'static str {
    let values: Vec<&str> = tests
        .iter()
        .map(|test| {
            test.get("result_index")
                .and_then(Value::as_u64)
                .and_then(|index| results.get(index as usize))
                .and_then(|result| result.get("status"))
                .and_then(Value::as_str)
                .filter(|status| {
                    ["ERRORED", "FAILED", "PASSED", "NOT_RUN", "SKIPPED"].contains(status)
                })
                .unwrap_or("NOT_RUN")
        })
        .collect();
    ["ERRORED", "FAILED", "PASSED", "NOT_RUN", "SKIPPED"]
        .into_iter()
        .find(|status| values.contains(status))
        .unwrap_or("NOT_RUN")
}

fn index_listing(pages: &[ItemPage]) -> String {
    let mut html = String::from("<section id=\"report-index\" aria-labelledby=\"report-index-title\"><h2 id=\"report-index-title\">Flows and tests</h2><p class=\"muted\">Reports from this invocation, in execution order.</p><table class=\"report-index-table\"><thead><tr><th scope=\"col\">Name</th><th scope=\"col\">Type</th><th scope=\"col\">Status</th><th scope=\"col\">Tests</th></tr></thead><tbody>");
    for page in pages {
        let name = escape(
            page.item
                .get("name")
                .and_then(Value::as_str)
                .unwrap_or("Unnamed test"),
        );
        let kind = if page.item.get("kind").and_then(Value::as_str) == Some("flow") {
            "Flow"
        } else {
            "Standalone test"
        };
        let label = match page.status {
            "PASSED" => "Passed",
            "FAILED" => "Failed",
            "ERRORED" => "Errored",
            "SKIPPED" => "Skipped",
            _ => "Not run",
        };
        let count = page.report.metadata["tests"].as_array().map_or(0, Vec::len);
        html.push_str(&format!("<tr data-status=\"{}\"><td><a href=\"{DIRECTORY}/{}\">{name}</a></td><td>{kind}</td><td><span class=\"badge\" data-status=\"{}\">{label}</span></td><td>{count}</td></tr>\n", page.status, page.filename, page.status));
    }
    html.push_str("</tbody></table>");
    if pages.is_empty() {
        html.push_str(
            "<p class=\"empty-state\">No flows or tests were selected for this invocation.</p>",
        );
    }
    html.push_str("</section>");
    html
}

fn stylesheet_link(href: &str) -> String {
    format!("<link rel=\"stylesheet\" href=\"{}\">", escape(href))
}

fn with_navigation(report: &HtmlReport, href: &str, stylesheet: &str) -> String {
    let navigation = format!("<main>\n<nav class=\"report-navigation\" aria-label=\"Reports\"><a href=\"{}\">All flows and tests</a></nav>", escape(href));
    render(report, &stylesheet_link(stylesheet)).replacen("<main>", &navigation, 1)
}

fn index_document(listing: &str, aggregate: &str) -> String {
    let style = stylesheet_link(&format!("{DIRECTORY}/{STYLESHEET}"));
    mark_index(format!(
        r#"<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>Vault · Report index</title>{style}</head>
<body><header class="masthead"><div class="brand"><span class="brand-mark" aria-hidden="true">V</span><span>vault <span class="brand-sub">/ report index</span></span></div><div class="header-actions"><span class="offline-label">Offline report</span><button id="theme-toggle" type="button" aria-label="Switch color theme">Dark theme</button></div></header><main><section class="run-intro"><div><h1>Test run reports</h1><p class="run-context">Open a flow or standalone test to inspect its execution.</p></div></section><nav class="report-navigation"><a href="{aggregate}">Full run report</a></nav>{listing}<footer>Generated by Vault<span>Keep this directory together to share the reports offline.</span></footer></main>
<script>(()=>{{const root=document.documentElement;const button=document.getElementById('theme-toggle');function theme(dark){{root.dataset.theme=dark?'dark':'light';button.textContent=dark?'Light theme':'Dark theme';button.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');}}theme(matchMedia('(prefers-color-scheme: dark)').matches);button.addEventListener('click',()=>theme(root.dataset.theme!=='dark'));}})();</script></body></html>"#
    ))
}

fn mark_index(html: String) -> String {
    html.replacen(
        "<!doctype html>",
        &format!("<!doctype html>\n{INDEX_MARKER}"),
        1,
    )
}

fn escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn url_segment(value: &str) -> String {
    value
        .bytes()
        .map(|byte| match byte {
            b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                (byte as char).to_string()
            }
            _ => format!("%{byte:02X}"),
        })
        .collect()
}

fn owned_files(directory: &Path) -> io::Result<BTreeSet<String>> {
    match fs::symlink_metadata(directory) {
        Ok(metadata) if !metadata.file_type().is_dir() => {
            return Err(invalid(
                directory,
                "expected a real generated directory, not a symlink or file",
            ))
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(BTreeSet::new()),
        Err(error) => return Err(context(directory, error)),
    }
    let marker = directory.join(OWNERSHIP);
    regular_file_or_absent(&marker)?;
    if !marker.exists() {
        if at(directory, fs::read_dir(directory))?.next().is_some() {
            return Err(invalid(
                directory,
                "refusing to use a nonempty directory without Vault's ownership marker",
            ));
        }
        return Ok(BTreeSet::new());
    }
    let value: Value = serde_json::from_slice(&at(&marker, fs::read(&marker))?)
        .map_err(|error| invalid(&marker, &error.to_string()))?;
    let names = value
        .get("files")
        .and_then(Value::as_array)
        .filter(|_| value.get("schema_version") == Some(&json!(1)))
        .ok_or_else(|| invalid(&marker, "invalid ownership marker"))?;
    names
        .iter()
        .map(|name| {
            let name = name
                .as_str()
                .ok_or_else(|| invalid(&marker, "invalid generated filename"))?;
            let valid = name == STYLESHEET
                || name
                    .strip_prefix("flow-")
                    .or_else(|| name.strip_prefix("test-"))
                    .and_then(|name| name.strip_suffix(".html"))
                    .is_some_and(|number| {
                        number.len() >= 3 && number.bytes().all(|byte| byte.is_ascii_digit())
                    });
            if !valid {
                return Err(invalid(&marker, "invalid generated filename"));
            }
            Ok(name.to_owned())
        })
        .collect()
}

fn write_ownership(directory: &Path, names: &BTreeSet<String>) -> io::Result<()> {
    atomic_write(
        &directory.join(OWNERSHIP),
        &json!({"schema_version":1, "files":names}).to_string(),
    )
}

fn regular_file_or_absent(path: &Path) -> io::Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if !metadata.file_type().is_file() => Err(invalid(
            path,
            "expected a regular file, not a symlink or directory",
        )),
        Ok(_) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(context(path, error)),
    }
}

fn aliases(first: &Path, second: &Path) -> bool {
    fs::canonicalize(first)
        .ok()
        .zip(fs::canonicalize(second).ok())
        .is_some_and(|(first, second)| first == second)
}

fn atomic_write(path: &Path, contents: &str) -> io::Result<()> {
    regular_file_or_absent(path)?;
    let parent = path.parent().unwrap_or(Path::new("."));
    let (temporary, mut file) = loop {
        let temporary: PathBuf = parent.join(format!(
            ".vault-report-{}-{}.tmp",
            std::process::id(),
            TEMP_ID.fetch_add(1, Ordering::Relaxed)
        ));
        match fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)
        {
            Ok(file) => break (temporary, file),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(context(path, error)),
        }
    };
    let result = (|| {
        file.write_all(contents.as_bytes())?;
        drop(file);
        fs::rename(&temporary, path)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    at(path, result)
}

fn at<T>(path: &Path, result: io::Result<T>) -> io::Result<T> {
    result.map_err(|error| context(path, error))
}
fn context(path: &Path, error: io::Error) -> io::Error {
    io::Error::new(error.kind(), format!("{}: {error}", path.display()))
}
fn invalid(path: &Path, message: &str) -> io::Error {
    context(path, io::Error::new(io::ErrorKind::InvalidInput, message))
}
